language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- ./create_config.sh
script:
- npm test
env:
  global:
  - secure: JUsx75PTPqq5E0TrNroxq5Tzb5yjumDg03tGwKFCrq/4cK/LfL83CaYwGJ4dNjAUkruDPHirCVOiiggCu8PjZqXnGjNUtEO+3Ao9ws9n3M/qmSzfLB3BCRINjsso4/zC7ymhPeH7YNq4VduJ2K1XmZ9zrS0gU8ViUq3sIft2bzw=
  - secure: AJDDn3doncp2zdWKaAK1lDleEol8DiHU23YiZeeGrLEgBnFP7UTCuZsDI0B5/pL26clI5OgZ7vwuSvArbWrJYHd83T74wf7eCXYHBI424N0QPjaKW3BZI5SvPu3lEldV6HiErnsCMzn5912O+ZABqppqMczV5xXkK7GqfN673g0=
  - secure: iH+9sMwtjeK/4wxIi4b3NgbCJbTtHB1ZYDQcy+QbmdLx5Mvy4yRqB5Q0ynBR8Q1odb5ugABYZKN4LWHZyUZIuDJw6h1Z9U9ugLZ7CNaDB7mLLC95O9A8BFfbRZqDRhwhdOUTgRKgbLIU2IAoY7Pl2GNQ7tlNK7ljdgSIIbByG14=
